[workspace]
resolver = "2"
members = ["packages/*"]

[workspace.dependencies]
axum = "0.7.4"
clap = { version = "4.5.1", features = ["derive", "env"] }
color-eyre = { version = "0.6.2", features = ["url", "issue-url"] }
tracing = { version = "0.1.40", features = ["log"] }
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }