[package]
name = "qcdn"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.35.1", features = ["full"] }
tokio-stream = "0.1.14"
axum = "0.7.2"
axum-macros = "0.4.0"
axum-htmx = "0.5.0"
tower-http = { version = "0.5.0", features = ["trace", "cors"] }
anyhow = "1.0.76"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
clap = { version = "4.4.11", features = ["derive", "env"] }
sqlx = { version = "0.7.3", features = [
  "runtime-tokio",
  "sqlite",
  "macros",
  "migrate",
] }
chrono = { version = "0.4.31", features = ["serde"] }
listenfd = "1.0.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tonic = { version = "0.10.2", features = ["channel"] }
tonic-build = "0.10.2"
tonic-types = "0.10.2"
tonic-health = "0.10.2"
prost = "0.12.3"
prost-types = "0.12.3"
uuid = { version = "1.6.1", features = ["serde", "v7"] }
async-channel = "2.1.1"
tokio-util = { version = "0.7.10", features = ["codec", "io"] }

[build-dependencies]
tonic-build = "0.10.2"
