[package]
name = "qcdn_web"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
qcdn_utils = { path = "../utils" }
qcdn_tracing_setup = { path = "../tracing_setup" }
qcdn_storage = { path = "../storage" }
qcdn_database = { path = "../database" }
clap.workspace = true
futures.workspace = true
dotenvy.workspace = true
color-eyre.workspace = true
tracing.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
chrono.workspace = true
thiserror.workspace = true
file-format.workspace = true
axum = "0.7.6"
axum-macros = "0.4.2"
tower-http = { version = "0.6.1", features = [
  "trace",
  "compression-gzip",
  "compression-deflate",
  "compression-br",
  "compression-zstd",
] }
