[package]
name = "database"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.34", features = ["serde"] }
diesel = { version = "2.1.4", default-features = false, features = [
  "extras",
  "sqlite",
  "r2d2",
  "serde_json",
  "libsqlite3-sys",
  "returning_clauses_for_sqlite_3_35",
] }
diesel-enum = "0.2.1"
serde = { version = "1.0.196", features = ["derive"] }
thiserror = "1.0.57"
tracing = { version = "0.1.40", features = ["async-await"] }
