[package]
name = "qcdn_database"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre.workspace = true
tracing.workspace = true
serde.workspace = true
chrono.workspace = true
diesel = { version = "2.1.4", default-features = false, features = [
  "extras",
  "sqlite",
  "r2d2",
  "serde_json",
  "libsqlite3-sys",
  "returning_clauses_for_sqlite_3_35",
] }
diesel-enum = "0.2.1"
diesel_migrations = { version = "2.1.0", features = ["sqlite"] }
thiserror = "1.0.57"
