[package]
name = "qcdn_proto_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.11.0", features = ["channel"] }
tonic-build = "0.11.0"
tonic-types = "0.11.0"
tonic-health = "0.11.0"
prost = "0.12.3"
prost-types = "0.12.3"

[build-dependencies]
tonic-build = "0.11.0"