[package]
name = "qcdn_proto_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic.workspace = true
tonic-build.workspace = true
tonic-types.workspace = true
tonic-health.workspace = true
prost.workspace = true
prost-types.workspace = true
clap.workspace = true

[build-dependencies]
clap.workspace = true
tonic-build.workspace = true
