[package]
name = "qcdn_manager"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qcdn_tracing_setup = { path = "../tracing_setup" }
qcdn_storage = { path = "../storage" }
qcdn_database = { path = "../database" }
qcdn_proto_server = { path = "../proto_server" }
dotenvy.workspace = true
clap.workspace = true
color-eyre.workspace = true
tracing.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
async-channel = "2.2.0"
