[package]
name = "qcdn_proto_server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
qcdn_database = { path = "../database" }
color-eyre.workspace = true
tracing.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-build.workspace = true
tonic-types.workspace = true
tonic-health.workspace = true
prost.workspace = true
prost-types.workspace = true
serde.workspace = true

[build-dependencies]
tonic-build.workspace = true
