[package]
name = "qcdn_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qcdn_utils = { path = "../utils" }
qcdn_tracing_setup = { path = "../tracing_setup" }
qcdn_proto_client = { path = "../proto_client" }
clap.workspace = true
futures.workspace = true
dotenvy.workspace = true
color-eyre.workspace = true
tracing.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tonic.workspace = true
chrono.workspace = true
file-format.workspace = true
filesize = "0.2.0"
ratatui = { version = "0.26.1", features = ["serde", "macros", "all-widgets"] }
crossterm = { version = "0.27.0", features = ["serde"] }
