[package]
name = "qcdn_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qcdn_utils = { path = "../utils" }
qcdn_tracing_setup = { path = "../tracing_setup" }
qcdn_proto_client = { path = "../proto_client" }
clap.workspace = true
dotenvy.workspace = true
color-eyre.workspace = true
tracing.workspace = true
