[package]
name = "qcdn_tracing_setup"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
color-eyre.workspace = true
tracing.workspace = true
tracing-error.workspace = true
tracing-subscriber.workspace = true
